esphome:
  name: mycoco

esp32:
  board: um_feathers2
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password


web_server:
  port: 5083
  local: true

ota:
  - platform: esphome
    password: !secret ota_password

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: true
  id: bus_a
  # frequency: 100kHz

sensor:
  - platform: scd4x
    update_interval: 10s
    automatic_self_calibration: true #TODO: mycoco should be manually calibrated
    i2c_id: bus_a
    co2:
      name: "myco_CO2"
    temperature:
      name: "myco_temperature"
    humidity:
      name: "myco_humidity"

# TODO: MQTT
# Push the data also to MQTT topics: 
# * CO2 espscd40/sensor/scd40_co2/state
# * Temperature espscd40/sensor/co2_temperature/state  
# * Humidity espscd40/sensor/co2_humidity/state
# mqtt:
#   broker: 192.168.XXX.XXX
#   port: 1883
#   username: "XXXX"
#   password: "XXXX"

# TODO : implement forced calibration
# on_...:
#   then:
#     - scd4x.perform_forced_calibration:
#         # Global Monthly Mean CO₂
#         # https://gml.noaa.gov/ccgg/trends/global.html
#         value: 426
#         id: my_scd41

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mycoco Fallback Hotspot"
    password: !secret fallback_password

captive_portal:
    
