esphome:
  name: mycoco

esp32:
  board: um_feathers2
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password


web_server:
  port: 5083
  local: true

ota:
  - platform: esphome
    password: !secret ota_password

i2c:
  sda: GPIO08
  scl: GPIO09
  scan: true
  id: bus_a
  # frequency: 100kHz
sensor:
  - platform: scd4x
    update_interval: 10s
    i2c_id: bus_a
    co2:
      name: "myco_CO2"
    temperature:
      name: "myco_temperature"
    humidity:
      name: "myco_humidity"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mycoco Fallback Hotspot"
    password: !secret fallback_password

captive_portal:
    
