---
esphome:
  name: cocolight
  on_boot:
    priority: -100   # low priority = runs after wifi + time are ready
    then:
      - wait_until:
          condition:
            time.has_time:
      - lambda: |-
          auto t = id(my_time).now();
          if (t.hour >= 8 && t.hour < 20) {
            id(light_1).turn_on().perform();
          } else {
            id(light_1).turn_off().perform();
          }

esp8266:
  board: sonoff_basic

logger:
  # baud_rate: 921600
  # hardware_uart: UART0
  level: DEBUG

wifi:
  networks:
    - ssid: !secret ssid_a
      password: !secret password_a
      manual_ip:
        static_ip: 192.168.1.100
        gateway: 192.168.1.1
        subnet: 255.255.255.0

    - ssid: !secret ssid_b
      password: !secret password_b
      #
      manual_ip:
        static_ip: 192.168.1.100
        gateway: 192.168.1.1
        subnet: 255.255.255.0
  ap:
    ssid: fallback_cocolight
    password: !secret fallback_wifi_password
  # options below seem needed to stabilize connection
  power_save_mode: none
  # fast_connect: on
  # output_power: 8.5
  # reboot_timeout: 15min

captive_portal:

web_server:
  port: 5083
  local: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key
#
ota:
  - platform: esphome
    password: !secret api_password

output:
  - platform: gpio
    pin: GPIO12
    id: relay_1

light:
  - platform: binary
    name: "My Light"
    id: light_1
    output: relay_1
    restore_mode: ALWAYS_OFF

time:
  - platform: sntp
    id: my_time
    timezone: "Europe/Paris"
    servers:
      # We use IP directly because of a limition
      # with static IP
      - 216.239.35.0   # time1.google.com
      - 216.239.35.4   # time2.google.com
      - 216.239.35.8   # time3.google.com
    on_time:
      - seconds: 0
        minutes: 0
        hours: 8
        then:
          - light.turn_on: light_1
      - seconds: 0
        minutes: 0
        hours: 20
        then:
          - light.turn_off: light_1
